FROM ubuntu:latest
LABEL maintainer "tangjicheng <tangjch15@gmail.com>"
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \ 
    apt install -y apache2 vim 

RUN rm -rf /var/www/html && mkdir -p /app && ln -s /app /var/www/html
RUN mkdir -p /var/lock/apache2

COPY ./sample /app

EXPOSE 80
WORKDIR /app

CMD ["/run.sh"]