name: "stage-2"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "input_1:0"
    data_type: TYPE_FP32
    dims: [ 1, 448, 448, 3]
  }
]

output [
  {
    name: "predictions_sigmoid"
    data_type: TYPE_FP32
    dims: [ 1, 9083]
  }
]

instance_group [{ kind: KIND_CPU }]