apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-http
spec:
  replicas: 1
  selector:
    app: simple
  template:
    metadata:
      name: simple
      labels:
        app: simple
    spec:
      containers:
        - name: simple
          image: tang2432/simple_server:v1
          ports:
            - containerPort: 8000
