apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test
  labels:
    name: ubuntu-test
spec:
  containers:
    - name: ubuntu-test
      image: ubuntu:latest
      env:
        - name: GET_HOSTS_FROM
          value: env
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379
